# Generated by Django 3.1.6 on 2021-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('link_path', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=16)),
                ('image_path', models.CharField(max_length=1000, unique=True)),
                ('file_size', models.FloatField()),
                ('pub_time', models.TimeField(verbose_name='time published')),
                ('open_time', models.TimeField(verbose_name='time opened')),
            ],
        ),
    ]
