# Generated by Django 3.1.6 on 2021-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='Error', max_length=32),
        ),
    ]
