# Generated by Django 3.1.6 on 2021-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0002_auto_20210216_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(default='null', max_length=16),
        ),
    ]
