# Generated by Django 3.1.6 on 2021-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0003_auto_20210216_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to='./upload/'),
        ),
    ]
