# Generated by Django 3.1.6 on 2021-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0004_auto_20210216_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image_path',
            field=models.CharField(max_length=1000),
        ),
    ]
