# Generated by Django 3.1.6 on 2021-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0007_auto_20210216_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.FloatField(default=0.0),
        ),
    ]
