# Generated by Django 3.1.6 on 2021-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0008_auto_20210216_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link_path',
            field=models.FileField(blank=True, null=True, upload_to='./upload/link'),
        ),
    ]
