# Generated by Django 3.1.6 on 2021-02-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0009_auto_20210216_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(unique=True, upload_to='./upload/file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='./upload/image'),
        ),
    ]
