# Generated by Django 3.1.6 on 2021-02-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0010_auto_20210217_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(unique=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='thumb'),
        ),
        migrations.AlterField(
            model_name='file',
            name='link_path',
            field=models.FileField(blank=True, null=True, upload_to='link'),
        ),
    ]
