# Generated by Django 3.1.6 on 2021-02-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0011_auto_20210217_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='audio')),
                ('title', models.CharField(max_length=32)),
                ('author', models.CharField(default='未知', max_length=32)),
                ('lyric', models.FileField(blank=True, null=True, upload_to='audio/lyric')),
                ('duration', models.FloatField(default=0.0)),
                ('bit_rate', models.IntegerField(default=0)),
                ('sample_rate', models.IntegerField(default=0)),
                ('channel', models.CharField(default='立体声', max_length=32)),
                ('album_image', models.FileField(blank=True, null=True, upload_to='audio/image')),
                ('album_title', models.CharField(blank=True, max_length=32, null=True)),
                ('size', models.FloatField(default=0.0)),
                ('record_date', models.DateField(blank=True, null=True, verbose_name='record date')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='time published')),
                ('open_time', models.DateTimeField(auto_now=True, verbose_name='time opened')),
                ('open_count', models.IntegerField(default=0)),
            ],
        ),
    ]
