# Generated by Django 3.1.6 on 2021-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0012_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='record_date',
        ),
        migrations.AddField(
            model_name='audio',
            name='album',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='audio/image'),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AddField(
            model_name='audio',
            name='recorded_date',
            field=models.CharField(default='2020', max_length=16),
        ),
        migrations.AlterField(
            model_name='audio',
            name='channel',
            field=models.IntegerField(default=0),
        ),
    ]
