# Generated by Django 3.1.6 on 2021-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0013_auto_20210217_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='media_type',
            field=models.CharField(default='未知', max_length=32),
        ),
    ]
