# Generated by Django 3.1.6 on 2021-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0014_audio_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='audio/images'),
        ),
    ]
