# Generated by Django 3.1.6 on 2021-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0015_auto_20210217_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.CharField(default='未知', max_length=64),
        ),
        migrations.AlterField(
            model_name='audio',
            name='recorded_date',
            field=models.CharField(default='2022', max_length=16),
        ),
    ]
